# This is a basic workflow to help you get started with Actions

name: Build and push to Dockerhub

# Controls when the action will run. 
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push master
        if: github.ref == 'refs/heads/master'
        id: docker_build_master
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: iddix/alertmanager-webhook-signald:master
      -
        name: Build and push dev branch
        if: github.ref != 'refs/heads/master'
        id: docker_build_dev
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: iddix/alertmanager-webhook-signald:develop
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
